version: '3'

services:
  ros1_melodic:
    build:
      context: .
      dockerfile: Dockerfile.ros1
    image: ros1_melodic_custom
    container_name: ros1_melodic
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /home/axioma/Proyectos-ROS/Proyectos-ros1-melodic:/
      - /dev:/dev
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    restart: unless-stopped
    command: bash -c "source /opt/ros/melodic/setup.bash && roscore & tail -f /dev/null"


  ros2_humble:
    build:
      context: .
      dockerfile: Dockerfile.ros2
    image: ros2_humble_custom
    container_name: ros2_humble
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /home/axioma/Proyectos-ROS/Proyectos-ros2-humble:/ros2_ws/src
      - /dev:/dev
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - ros1_melodic
    restart: unless-stopped
    command: tail -f /dev/null

  bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    container_name: ros_bridge
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    privileged: true
    depends_on:
      - ros1_melodic
      - ros2_humble
    restart: unless-stopped
    # Agregar comando para iniciar el bridge automáticamente:
    command: bash -c "sleep 5 && source /opt/ros/melodic/setup.bash && source /opt/ros/humble/setup.bash && source /bridge_ws/install/setup.bash && ros2 run ros1_bridge dynamic_bridge --bridge-all-topics"