version: '3'

services:
  ros1_melodic:
    build:
      context: .
      dockerfile: Dockerfile.ros1
    image: ros1_melodic_custom
    container_name: ros1_melodic
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /home/axioma/Proyectos-ROS/Proyectos-ros1-melodic:/ros1_ws/src
      - /dev:/dev
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    command: bash -c "roscore & tail -f /dev/null"

  ros2_humble:
    build:
      context: .
      dockerfile: Dockerfile.ros2
    image: ros2_humble_custom
    container_name: ros2_humble
    # Quitar network_mode: "host" para usar mapeo de puertos
    privileged: true
    ports:
      - "7400-7500:7400-7500/udp"  # Mapeo correcto de puertos UDP para DDS
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=0
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /home/axioma/Proyectos-ROS/Proyectos-ros2-humble:/ros2_ws/src
      - /dev:/dev
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - ros1_melodic
    command: tail -f /dev/null